// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpyHZ5geBbj3I5LGqxI2uXqdXK7vJCwe0',
    appId: '1:831855477838:web:0dba414b168035a8626f1f',
    messagingSenderId: '831855477838',
    projectId: 'todaapp-4a784',
    authDomain: 'todaapp-4a784.firebaseapp.com',
    storageBucket: 'todaapp-4a784.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG0-Gk-j2aN8803l5DnijQuvGKssls5r8',
    appId: '1:831855477838:android:e5806a7a00b5a899626f1f',
    messagingSenderId: '831855477838',
    projectId: 'todaapp-4a784',
    storageBucket: 'todaapp-4a784.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7lVnUIAr18rttM4m7JDT3w7bdgH-Au_s',
    appId: '1:831855477838:ios:e1522f2b44d82f22626f1f',
    messagingSenderId: '831855477838',
    projectId: 'todaapp-4a784',
    storageBucket: 'todaapp-4a784.appspot.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7lVnUIAr18rttM4m7JDT3w7bdgH-Au_s',
    appId: '1:831855477838:ios:ba7968e33389573e626f1f',
    messagingSenderId: '831855477838',
    projectId: 'todaapp-4a784',
    storageBucket: 'todaapp-4a784.appspot.com',
    iosBundleId: 'com.example.toDoApp.RunnerTests',
  );
}
